missiles:
    SMALLMISSILE:
        speed: 2
        range: 750
        power: 3
        accuracy: 100
    SMALLMISSILEHE:
        speed: 1
        range: 600
        power: 3.5
        accuracy: 120
    SMALLMISSILELR:
        speed: 2
        range: 700
        power: 3
        accuracy: 100
    SMALLMISSILEAC:
        speed: 2
        range: 700
        power: 3
        accuracy: 60
    ANTIAIRMISSILE:
        speed: 5
        range: 600
        power: 4
        accuracy: 0
    MISSILE:
        speed: 2.5
        range: 1000
        power: 4.5
        accuracy: 80
    MISSILEHE:
        speed: 2
        range: 1000
        power: 5
        accuracy: 100
    MISSILELR:
        speed: 2.5
        range: 1400
        power: 4.5
        accuracy: 80
    MISSILEAC:
        speed: 2.5
        range: 1000
        power: 4.5
        accuracy: 50
    MISSILEAPONE:
        speed: 2
        range: 1550
        power: 3.5
        accuracy: 40
    MISSILEAPTWO:
        speed: 2.5
        range: 1700
        power: 4
        accuracy: 20
    MISSILEAPTHR:
        speed: 4
        range: 1850
        power: 4.5
        accuracy: 10
    MISSILEGAS:
        speed: 3
        range: 1600
        power: 0.5
        accuracy: 80
    MISSILEEXCAV:
        speed: 0.5
        range: 100
        power: 10
        accuracy: 50
    MISSILESTICK:
        speed: 4
        range: 1600
        power: 1
        accuracy: 70
    MISSILEICBM:
        speed: 5
        range: 7000
        power: 8
        accuracy: 50
    MISSILECLUSTER:
        speed: 3.5
        range: 1600
        power: 4
        accuracy: 80
    MISSILENAPALM:
        speed: 3
        range: 1600
        power: 2
        accuracy: 140
    MISSILEADV:
        speed: 4
        range: 2000
        power: 4
        accuracy: 40
    MISSILEHEADV:
        speed: 3.5
        range: 2000
        power: 5
        accuracy: 35
    MISSILELRADV:
        speed: 4.5
        range: 2500
        power: 4
        accuracy: 40
    MISSILEACADV:
        speed: 4
        range: 2000
        power: 4.5
        accuracy: 20
    ANTIELYTRAMISSILE:
        speed: 6
        range: 700
        power: 4
        accuracy: 0

mine:
    explosivepower: 8
    # Amount of random damage to apply to the receiving player
    maxranddamage: 10

# 在 lang 文件夹中可以找到相应的翻译
# 在此填入不带后缀的文件名
translation-pack: pack-CN

# 不要改动该选项，将在第一次启动后生成语言文件
saved-packs:
    - pack-CN

logging:
    logMissileShots: true
    # BROADCASTS TO ALL PLAYERS THAT A MISSILE WAS SHOT
    broadcastMissileShots: false
    # Seconds to wait before broadcasting the missile being shot
    waitTimeBeforeBroadcast: 20

other:
    #How long until cleanup of armour stands (ticks)
    cleanup-wait-time: 1200

options:
    auto-update: true